name: 'publish docs'

# Publish when a git tag is pushed to main
on:
  push:
    branches:
      - add_docs
#    tags:
#      - '*'

jobs:
  publish_sphinx_docs:
    name: Publish Sphinx Docs
    runs-on: ubuntu-latest
    run: |
      python -m pip install --upgrade pip
      pip install .[dev]
    steps:
    - uses: neuroinformatics-unit/actions/publish_sphinx_docs@v1
      with:
        secret_input: ${{ secrets.GITHUB_TOKEN }}
