name: 'Sphinx Docs Publish'
description: 'Builds sphinx docs and publishes them to GitHub Pages'

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v3

  - name: Setup Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.x'

  - name: Upgrade pip
    shell: bash
    run: |
      # install pip=>20.1 to use "pip cache dir"
      python3 -m pip install --upgrade pip
  - name: Get pip cache dir
    shell: bash
    id: pip-cache
    run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

  - name: Cache dependencies
    uses: actions/cache@v3
    with:
      path: ${{ steps.pip-cache.outputs.dir }}
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-
  - name: Install dependencies
    shell: bash
    run: python3 -m pip install -r ./docs/requirements.txt

  # needs to have sphinx.ext.githubpages in conf.py extensions list
  - name: Building documentation
    shell: bash
    run: |
      sphinx-build docs/source docs/build -W -T -b html
  - name: Deploy
    env:
      GITHUB_TOKEN: ${{ inputs.secret_input }}
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ env.GITHUB_TOKEN }}
      publish_dir: ./docs/build

"""
name: 'publish docs'

# Publish when a git tag is pushed to main
on:
  push:
    branches:
      - add_docs
#    tags:
#      - '*'

jobs:
  publish_sphinx_docs:
    name: Publish Sphinx Docs
    runs-on: ubuntu-latest
    steps:
    - uses: neuroinformatics-unit/actions/publish_sphinx_docs@v1
      with:
        secret_input: ${{ secrets.GITHUB_TOKEN }}
"""
